### PR TITLE
Universal Test Harness

### PR DESCRIPTION
**Pull request by thecodedrift**
This is a complete changeset for the AMDJS test suite.
- We are no longer dependent on DOH, instead using a standalone test harness, mirroring the functionality of compliance frameworks like InteroperableJS (the commonJS test suite)
- Easy addition of new frameworks in the auto-run harness
- Integration with existing test suites by implementing `window. amdJSPrint(message, pass | fail)`
- All libraries upgraded to their latest revisions as of 1fc5195a:
  - RequireJS @ 2.1.5
  - Needs JS @ a915dce3f9
  - Inject @ 0.4.1
  - lsjs @ e61412da (disabled pending issue below)

Outstanding Issues
- @rbackhouse lsjs seems to still have a circular reference problem during module resolution. This seems to be a transient issue. It is reproducible in the basic_simple test case (lowest number of moving parts). Specifically, it gets caught in an infinite loop resolving `["a", "b"]` dependencies. After localStorage is loaded, the problem does not reproduce. I'll open a ticket and add it to this PR.
- The stuff in draft form around common config could use some shoring up.

### CODE REVIEW

**Comment by rbackhouse** [comment]
@Jakobo I have to wonder why the lsjs problem is not present when run with the old test harness.

**Comment by thecodedrift** [comment]
Me too. Hit me up on gtalk jakob at felocity.com and maybe we can screenshare / work through this. It actually looks like DOH's isolation wasn't true isolation tests, as localStorage would end up primed between runs.

I've gotten it down to a pretty reproducible test case. If we can solve it before merge, all the better.

**Comment by rbackhouse** [comment]
Ok, then it might be best to leave lsjs disabled for now. I'm not actively developing it at the moment so it might be a while before i get to take a look at the issue

**Comment by thecodedrift** [comment]
Alright. At the very least, I want to add a commit so reproducing is as simple as uncomment lsjs, run server, hit reproduction URL.

**Comment by thecodedrift** [comment]
I've added https://github.com/zazl/lsjs/issues/3 to track the outstanding lsjs item. Includes full reproduction steps.

**Comment by rbackhouse** [comment]
Ok that works for me. Thanks

**Pull request merged**
